title: Base11 Studios
url: "https://base11studios.com"
baseurl:
google_analytics_key:
google_maps_javascript_api_key: AIzaSyAvoy9lyc8Whs9RejsyHHzfWfv6aNao79k
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Mobile application development in Cincinnati, OH.

# Author details for the jekyll-seo-tag gem
author:
  name: "Base11 Studios"
  email: "dan@base11studios.com"
  twitter: base11studios

# Social details for the jekyll-seo-tag gem
social:
  name: Base11 Studios
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
